var annotated_dup =
[
    [ "Callback", "structCallback.html", "structCallback" ],
    [ "CFD_t", "structCFD__t.html", "structCFD__t" ],
    [ "cFILE_t", "structcFILE__t.html", "structcFILE__t" ],
    [ "cJSON", "structcJSON.html", "structcJSON" ],
    [ "cJSON_Hooks", "structcJSON__Hooks.html", "structcJSON__Hooks" ],
    [ "cMAT_t", "structcMAT__t.html", "structcMAT__t" ],
    [ "cVEC_t", "structcVEC__t.html", "structcVEC__t" ],
    [ "element_size_t", "structelement__size__t.html", "structelement__size__t" ],
    [ "engine_t", "structengine__t.html", "structengine__t" ],
    [ "error", "structerror.html", "structerror" ],
    [ "F_coefficients_t", "structF__coefficients__t.html", "structF__coefficients__t" ],
    [ "fluid_t", "structfluid__t.html", "structfluid__t" ],
    [ "geometry_t", "structgeometry__t.html", "structgeometry__t" ],
    [ "in_t", "structin__t.html", "structin__t" ],
    [ "internal_hooks", "structinternal__hooks.html", "structinternal__hooks" ],
    [ "log_Event", "structlog__Event.html", "structlog__Event" ],
    [ "mesh_data_t", "structmesh__data__t.html", "structmesh__data__t" ],
    [ "mesh_element_t", "structmesh__element__t.html", "structmesh__element__t" ],
    [ "mesh_nodes_t", "structmesh__nodes__t.html", "structmesh__nodes__t" ],
    [ "mesh_t", "structmesh__t.html", "structmesh__t" ],
    [ "method_index_t", "structmethod__index__t.html", "structmethod__index__t" ],
    [ "method_state_t", "structmethod__state__t.html", "structmethod__state__t" ],
    [ "method_t", "structmethod__t.html", "structmethod__t" ],
    [ "option", "structoption.html", "structoption" ],
    [ "out_t", "structout__t.html", "structout__t" ],
    [ "parse_buffer", "structparse__buffer.html", "structparse__buffer" ],
    [ "position", "structposition.html", "structposition" ],
    [ "printbuffer", "structprintbuffer.html", "structprintbuffer" ],
    [ "residual_t", "structresidual__t.html", "structresidual__t" ],
    [ "SCGS_t", "structSCGS__t.html", "structSCGS__t" ],
    [ "scheme_convection_t", "structscheme__convection__t.html", "structscheme__convection__t" ],
    [ "scheme_diffusion_t", "structscheme__diffusion__t.html", "structscheme__diffusion__t" ],
    [ "schemes_t", "structschemes__t.html", "structschemes__t" ],
    [ "under_relaxation_factors_t", "structunder__relaxation__factors__t.html", "structunder__relaxation__factors__t" ],
    [ "Vanka_t", "structVanka__t.html", "structVanka__t" ]
];