name: Doxygen Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."
        enable-latex: false

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.doxygen/html
